name: Kodi Addon Checker

on:
  workflow_dispatch:

jobs:
  kodi_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install kodi-addon-checker
        run: pip install kodi-addon-checker

      - name: Run kodi-addon-checker
        run: kodi-addon-checker . --branch piers | tee output.txt