name: Auto-zip plugin on push

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  zip-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set repo name in env var
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Create plugin folder and zip it
        run: |
          mkdir -p temp/${REPO_NAME}
          shopt -s extglob
          cp -r !(temp|*.zip|.git|.github) temp/${REPO_NAME}/
          zip -r ${REPO_NAME}.zip temp/${REPO_NAME}

      - name: Remove temp folder
        run: rm -rf temp

      - name: Commit and push new zip
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add ${REPO_NAME}.zip
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          
          git commit -m "Update zip file on push"
          git push
